# Generated by Django 6.0.4 on 2026-04-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pedidos',
            fields=[
                ('idPedidos', models.IntegerField(db_column='idPedidos', primary_key='idPedidos', serialize=False)),
            ],
            options={
                'db_table': 'comida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios_db',
            fields=[
                ('idUsuarios_db', models.IntegerField(db_column='idUsuarios', primary_key='idUsuarios', serialize=False)),
                ('typeUsers_db', models.CharField(db_column='typeUsers', max_length=30)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
