# Generated by Django 6.0.4 on 2026-04-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comida',
            fields=[
                ('idComida', models.IntegerField(db_column='idComida', primary_key='idComida', serialize=False)),
                ('info', models.CharField(db_column='info', max_length=50)),
                ('cantidad', models.IntegerField()),
                ('direccion', models.CharField(db_column='direccion', max_length=100)),
                ('persona', models.CharField(db_column='persona', max_length=50)),
            ],
            options={
                'db_table': 'comida',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='pedidos',
            table='pedidos',
        ),
    ]
