# Generated by Django 6.0.4 on 2026-04-09 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': False},
        ),
    ]
