# Generated by Django 6.0.4 on 2026-04-09 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuarios_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuarios',
            table='usuarios',
        ),
    ]
